modLoader = "javafml"
loaderVersion = "[43,)"
license = "All rights reserved"

[[mods]]
    modId = "jmc"
    version = "${version}"
    displayName = "Just More Cakes!"
    #updateJSONURL="http://myurl.me/"
    displayURL = "https://www.curseforge.com/minecraft/mc-mods/just-more-cakes"
    issueTrackerURL = "https://github.com/MincraftEinstein/JustMoreCakes/issues"
    logoFile = "pack.png"
    credits = "Me the mod author"
    authors = "MincraftEinstein"
    displayTest = "MATCH_VERSION"
    description = '''
A simple mod that adds 30+ new cakes to Minecraft
'''

[modproperties.jmc]
    catalogueImageIcon = "pack.png"
    configuredBackground = "minecraft:textures/block/bricks.png"

[[dependencies.jmc]]
    modId = "forge"
    mandatory = true
    versionRange = "[43.1.65,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.jmc]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.2, 1.20]"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.jmc]]
    modId = "jei"
    mandatory = false
    versionRange = "[12.3.0.18,)"
    ordering = "NONE"
    side = "CLIENT"

[[dependencies.jmc]]
    modId = "cake-chomps"
    mandatory = false
    versionRange = "[6.0.1+1.19.3,)"
    ordering = "NONE"
    side = "CLIENT"
